import { Avatar } from "./types";

export const mockAvatars: Avatar[] = [
    { id: 'zarnok', name: 'Zarnok', tagline: 'Master of Cosmic Logic', intro: 'You process the world through logic and structure. Clarity grounds you — there’s comfort in order, patterns, and understanding how things fit together. You rarely act on impulse, preferring to analyze before you act. Your matter-of-fact nature keeps chaos at bay, yet beneath the data, you move with quiet defiance — driven to solve things efficiently and elegantly.', image: '/avatars/zarnok.png', forces: ['Icy-7', 'Orbitz'], counterforce: 'Captain Flarb' },
    { id: 'icy-7', name: 'Icy-7', tagline: 'AI Sage of Frozen Jupiter', intro: 'You possess a calm, balanced, and well-rounded mind. Resourceful and observant, you rarely rush — your strength lies in patience and understanding. When others react, you reflect. You value peace and reason, and there’s quiet depth in how you care for the balance of all things.', image: '/avatars/ic7.png', forces: ['Zarnok', 'Orbitz'], counterforce: 'Blip' },
    { id: 'orbitz', name: 'Orbitz', tagline: 'Reflective Explorer of Neptune', intro: 'You find meaning in everything — in silence, in laughter, in the way stars seem to wink back. Your thoughts drift between reason and wonder, discovering ideas others might miss. You experiment freely, embracing paradox as part of your nature. The galaxy feels like a conversation, and you’re always somewhere between its muse and its dreams.', image: '/avatars/orbitz.png', forces: ['Zarnok', 'Icy-7'], counterforce: 'Glimbo' },
    { id: 'blip', name: 'Blip', tagline: 'Empath of the Moon Colonies', intro: 'You navigate the world by feeling, not formula. Your moods are your compass — vivid, shifting, and alive. You sense the energy of people and moments instinctively, responding in ways that feel natural and sincere. Adaptable and resilient, you shine brightest when emotions find harmony.', image: '/avatars/blip.png', forces: ['Glimbo', 'Captain Flarb'], counterforce: 'Icy-7' },
    { id: 'glimbo', name: 'Glimbo', tagline: 'Influencer of the Constellations', intro: 'You move through life like a song — every beat, sound, and rhythm fuels your next move. Logic takes a back seat to resonance; you know when something feels right. Your world flows by instinct, not formula, and your path often hums before it makes sense. When life turns noisy, you turn dissonance into melody — and zombies into headbangers.', image: '/avatars/glimbo.png', forces: ['Blip', 'Captain Flarb'], counterforce: 'Orbitz' },
    { id: 'flarb', name: 'Captain Flarb', tagline: 'Starship Navigator of the Sun', intro: 'You live boldly and love momentum. Every choice feels like a declaration, and hesitation isn’t your style. You thrive when passion fuels the mission — leading, performing, or standing firm for what matters. Life’s too short for half-measures, and you’d rather soar than settle. There’s never a dull moment when you’re around.', image: '/avatars/flarb.png', forces: ['Blip', 'Glimbo'], counterforce: 'Zarnok' },
];